Tgp 1924/create a new endpoint in data store to clear the db collections
hmrc/trader-goods-profiles-data-store pull request #33
Opened 2024-07-22 11:28 UTC by pauloncast

2024-07-22 14:05 UTC, yohan-oc commented on test/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileControllerSpec.scala
> +
DELETE ?

2024-07-23 11:29 UTC, AmarkumarJagtap approved these changes

2024-07-23 12:49 UTC, liandra-giacomine requested changes
We shouldn't be adding functionality in here to facilitate tests, this can be done in the performance test itself

2024-07-24 08:19 UTC, liandra-giacomine commented on app/uk/gov/hmrc/tradergoodsprofilesdatastore/controllers/ProfileController.scala
> +      Future.successful(NotFound)
not sure about returning not found here, maybe internals server error?

2024-07-24 08:19 UTC, liandra-giacomine commented on app/uk/gov/hmrc/tradergoodsprofilesdatastore/repositories/ProfileRepository.scala
> +  def deleteAll: Future[Boolean] =
can you return Future[Done] here, a boolean doesn't represent anything here

2024-07-24 11:56 UTC, liandra-giacomine approved these changes

2024-07-24 11:57 UTC, merged