TGP-1061: changed to new getRecords url
hmrc/trader-goods-profiles-data-store pull request #9
Opened 2024-06-17 14:14 UTC by besscerule

2024-06-17 14:15 UTC, liandra-giacomine submitted a review, later dismissed

2024-06-18 15:32 UTC, vinoocs requested changes

2024-06-18 15:32 UTC, vinoocs commented on app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/response/GoodsItemRecords.scala
>          "comcode"                  -> goodsItemRecords.comcode,
the accreditationStatus has been renamed to adviceStatus now in API - we shouldn't be removing this I suppose.

2024-06-18 15:32 UTC, vinoocs commented on app/uk/gov/hmrc/tradergoodsprofilesdatastore/models/response/GoodsItemRecords.scala
>          "comcode"                  -> goodsItemRecords.comcode,
Also, the test cases need to updated for the urls. I updated them in my PR https://github.com/hmrc/trader-goods-profiles-data-store/pull/10

2024-06-18 15:42 UTC, closed without merging